name: field_master
description: A smart farming application for field data management.
version: 1.0.0+1

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    http: ^1.1.0
    charts_flutter: ^0.12.0
    intl: ^0.18.0
    shared_preferences: ^2.2.0
    provider: ^6.0.5
    firebase_core: ^2.24.2
    firebase_auth: ^4.15.3
    fl_chart: ^0.65.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/icons/

    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Bold.ttf
                weight: 700
